#!/bin/bash
# ============================================
# FIX PUBLIC STORAGE ACCESS ON VPS
# Kong requires apikey header even for public bucket objects.
# This script patches Nginx to inject the anon key for public storage routes.
# Run: sudo bash /var/www/justachat/public/vps-deploy/fix-storage-public-access.sh
# ============================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo ""
echo "============================================"
echo -e "${CYAN}  FIX PUBLIC STORAGE ACCESS${NC}"
echo "============================================"
echo ""

# Get anon key from frontend .env
DEPLOY_DIR="${DEPLOY_DIR:-/var/www/justachat}"
SUPABASE_DIR="${SUPABASE_DIR:-/home/unix/supabase/docker}"

# Try to extract anon key from frontend .env
ANON_KEY=""
if [ -f "$DEPLOY_DIR/.env" ]; then
  ANON_KEY=$(grep -E "^VITE_SUPABASE_PUBLISHABLE_KEY=" "$DEPLOY_DIR/.env" | cut -d'=' -f2- | tr -d '"' | tr -d "'")
fi

# Fallback: try Docker .env
if [ -z "$ANON_KEY" ] && [ -f "$SUPABASE_DIR/.env" ]; then
  ANON_KEY=$(grep -E "^ANON_KEY=" "$SUPABASE_DIR/.env" | cut -d'=' -f2- | tr -d '"' | tr -d "'")
fi

if [ -z "$ANON_KEY" ]; then
  echo -e "${RED}ERROR: Could not find ANON_KEY in .env files${NC}"
  echo "Checked:"
  echo "  - $DEPLOY_DIR/.env (VITE_SUPABASE_PUBLISHABLE_KEY)"
  echo "  - $SUPABASE_DIR/.env (ANON_KEY)"
  exit 1
fi

echo -e "${GREEN}✓ Found anon key${NC}"
echo "  Key: ${ANON_KEY:0:20}...${ANON_KEY: -10}"

# Create the snippet
SNIPPET_FILE="/etc/nginx/snippets/storage-public.conf"
echo ""
echo -e "${YELLOW}Creating Nginx snippet for public storage...${NC}"

cat > /tmp/storage-public.conf << EOF
# Public storage bypass - inject apikey for Kong
# Auto-generated by fix-storage-public-access.sh
location ~ ^/storage/v1/object/public/ {
    proxy_pass http://127.0.0.1:8000;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    
    # Inject anon key for Kong - public objects don't need user auth
    proxy_set_header apikey '$ANON_KEY';
    
    # Cache headers for images
    proxy_cache_valid 200 1h;
    add_header Cache-Control "public, max-age=3600";
}
EOF

sudo mv /tmp/storage-public.conf "$SNIPPET_FILE"
sudo chmod 644 "$SNIPPET_FILE"
echo -e "${GREEN}✓ Created $SNIPPET_FILE${NC}"

# Check if snippet is already included in main config
NGINX_CONF="/etc/nginx/sites-available/justachat"
if [ ! -f "$NGINX_CONF" ]; then
  echo -e "${RED}ERROR: Nginx config not found at $NGINX_CONF${NC}"
  exit 1
fi

# Backup
sudo cp "$NGINX_CONF" "$NGINX_CONF.bak.$(date +%Y%m%d%H%M%S)"

# Check if already included
if grep -q "include snippets/storage-public.conf" "$NGINX_CONF"; then
  echo -e "${YELLOW}⚠ Snippet already included in nginx config${NC}"
else
  echo ""
  echo -e "${YELLOW}Patching nginx config to include snippet...${NC}"
  
  # Insert the include statement right after "server {" line inside the HTTPS server block
  # We need to find the SSL server block and add it there
  # The safest approach: add it before the first "location" line in the SSL block
  
  # Create a temp file with the patch
  sudo awk '
    /listen 443 ssl/ { in_ssl_block = 1 }
    in_ssl_block && /location \// && !snippet_added {
      print "    # Public storage - inject apikey for Kong"
      print "    include snippets/storage-public.conf;"
      print ""
      snippet_added = 1
    }
    { print }
  ' "$NGINX_CONF" > /tmp/nginx-patched.conf
  
  sudo mv /tmp/nginx-patched.conf "$NGINX_CONF"
  echo -e "${GREEN}✓ Added include statement to nginx config${NC}"
fi

# Test and reload
echo ""
echo -e "${YELLOW}Testing nginx configuration...${NC}"
if sudo nginx -t 2>&1; then
  echo -e "${GREEN}✓ Nginx config test passed${NC}"
  
  echo ""
  echo -e "${YELLOW}Reloading nginx...${NC}"
  sudo systemctl reload nginx
  echo -e "${GREEN}✓ Nginx reloaded${NC}"
else
  echo -e "${RED}ERROR: Nginx config test failed!${NC}"
  echo "Restoring backup..."
  sudo cp "$NGINX_CONF.bak."* "$NGINX_CONF" 2>/dev/null || true
  exit 1
fi

# Test the fix
echo ""
echo -e "${YELLOW}Testing public storage access...${NC}"
sleep 1

# Try to fetch a public storage URL (any file in avatars bucket)
TEST_RESULT=$(curl -s -o /dev/null -w "%{http_code}" "https://justachat.net/storage/v1/object/public/avatars/" 2>/dev/null || echo "000")

if [ "$TEST_RESULT" = "200" ] || [ "$TEST_RESULT" = "404" ]; then
  # 200 = found, 404 = path not found but Kong didn't block it
  echo -e "${GREEN}✓ Public storage access working (HTTP $TEST_RESULT)${NC}"
else
  echo -e "${YELLOW}⚠ Got HTTP $TEST_RESULT - may need to test with actual file${NC}"
fi

echo ""
echo "============================================"
echo -e "${GREEN}  PUBLIC STORAGE FIX COMPLETE${NC}"
echo "============================================"
echo ""
echo "Test by uploading an image in chat or opening this URL:"
echo "  https://justachat.net/storage/v1/object/public/avatars/"
echo ""
